interface_langs = {
    "en": {
        "title": "Unsub Dwarf",
        "label": "How many emails to check? Enter a number:",
        "start": "Start",
        "stop": "Stop",
        "error": "Error: enter a number.",
        "launch": "Launch",
        "processing": "Processing emails: {limit}",
        "no_more_messages": "No more emails found.",
        "cancelled": "Execution stopped.",
        "email_processing": "Processing email...",
        "from": "From:",
        "unsubscribe_header_found": "Unsubscribe",
        "email_sent": "Unsubscribe email sent",
        "found_in_body": "Unsubscribe link found in email body",
        "deleted": "Email moved to trash",
        "delete_error": "Error while deleting email:",
        "probably_spam": "Email '{subject}' from {sender} looks like spam → deleting",
        "skipped": "Email skipped — doesn’t look like spam",
        "process_error": "Error while processing email:",
        "cancel": "Stopped by user",
    },
    "ru": {
        "title": "Гном Отписок",
        "label": "Сколько писем проверить? Введите число:",
        "start": "Начать",
        "stop": "Закончить",
        "error": "Ошибка: введите число.",
        "launch": "Запуск",
        "processing": "Обрабатываем писем: {limit}",
        "no_more_messages": "Больше писем не найдено.",
        "cancelled": "Остановка выполнения.",
        "email_processing": "Обработка письма...",
        "from": "От:",
        "unsubscribe_header_found": "Отписка",
        "email_sent": "Отписка по email отправлена",
        "found_in_body": "Найдена отписка в теле письма",
        "deleted": "Письмо отправлено в корзину",
        "delete_error": "Ошибка при удалении письма:",
        "probably_spam": "Письмо '{subject}' от {sender} похоже на рекламу → удаляю",
        "skipped": "Письмо пропущено — не похоже на спам",
        "process_error": "Ошибка при обработке письма:",
        "cancel": "Остановлено пользователем",

    },
    "cz": {
        "title": "Gnóm Odhlášek",
        "label": "Kolik e-mailů zkontrolovat? Zadejte číslo:",
        "start": "Spustit",
        "stop": "Ukončit",
        "error": "Chyba: zadejte číslo.",
        "launch": "Spuštění",
        "processing": "Zpracovávám e-maily: {limit}",
        "no_more_messages": "Žádné další e-maily nebyly nalezeny.",
        "cancelled": "Zpracování bylo zrušeno.",
        "email_processing": "Zpracovávám e-mail...",
        "from": "Od:",
        "unsubscribe_header_found": "Odhlášení",
        "email_sent": "E-mail s odhlášením byl odeslán",
        "found_in_body": "Odkaz na odhlášení nalezen v těle zprávy",
        "deleted": "E-mail přesunut do koše",
        "delete_error": "Chyba při mazání e-mailu:",
        "probably_spam": "E-mail '{subject}' od {sender} vypadá jako spam → mažu",
        "skipped": "E-mail přeskočen — nevypadá jako spam",
        "process_error": "Chyba při zpracování e-mailu:",
        "cancel": "Zastaveno uživatelem",

    },
}
